name: Docker Image CI

on:
  push:
    tags:
     - v**
    branches:
      - 'upcoming/*'
      - 'master'
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # Ensure this is lowercase

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.1.0
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.5.0
      with:
        version: latest
        install: true
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: Dockerfile
        platforms: linux/arm/v7,linux/arm64,linux/amd64
        push: true # Set to true to push the image to the registry
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME | toLowerCase }}:latest # Convert to lowercase

